version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    container_name: postgres-gm-fasters-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '${DATABASE_PORT}:5432'

  api:
    container_name: nest-gm-fasters-api
    #image: nestjs-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      # ✨ Target the dev stage
      target: dev
    # Mount host directory to docker container to support watch mode
    volumes:
      - .:/app
      # This ensures that the NestJS container manages the node_modules folder
      # rather than synchronizes it with the host machine
      - /app/node_modules
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - postgres
    command: npm start


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4-gm-fasters
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DATABASE_ADM_USER}
      - PGADMIN_DEFAULT_PASSWORD=${DATABASE_ADM_PASS}
    ports:
      - '5050:80'
    depends_on:
      - postgres
